highreward_dev_database:
  target: prod
  outputs:
    prod:
      type: postgres
      host: localhost
      user: root
      password: '${DB_PASSWORD}'
      port: 5433
      dbname: high_rewards
      schema: dbt
      sslmode: disable
