name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt==1.8.4
        pip install lightdash==0.1184.0
    - name: Set up SSH tunnel
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -fN -L 5433:high-rewards-aurora-postgresql-reader.cjy248yiebxq.us-east-1.rds.amazonaws.com:5432 ubuntu@52.87.194.221

    - name: Copy profiles.yml
      run: |
        mkdir -p ~/.dbt
        cp ./profiles.yml ~/.dbt/profiles.yml

    - name: Run dbt debug
      run: dbt debug

    - name: Run dbt with prod target
      run: dbt run --target prod

    - name: Generate Lightdash YAML files
      run: echo "yes" | lightdash generate --target prod

    - name: Deploy Lightdash
      run: lightdash deploy --target prod
